version: '3'

services:
  db:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
     - "3306:3306"
    networks:
      tp5-bcc362:
        ipv4_address: 10.5.0.5

  api:
    container_name: tp5-server
    build: ./API/
    ports:
     - "3265:3000"
    networks:
      tp5-bcc362:
        ipv4_address: 10.5.0.6
    depends_on:
     - db
  front:
    container_name: tp5-interface
    build: ./Front/
    ports:
     - "3266:3000"
    networks:
      tp5-bcc362:
        ipv4_address: 10.5.0.7
    depends_on:
     - api

networks:
  tp5-bcc362:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
