version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'tp5'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
      tp5-bcc362:
        ipv4_address: 10.5.0.5
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

  api:
    container_name: tp5-server
    build: ./API/
    ports:
     - "3265:3000"
    networks:
      tp5-bcc362:
        ipv4_address: 10.5.0.6
    depends_on:
     - db
     
  front:
    container_name: tp5-interface
    build: ./Front/
    ports:
     - "3266:3000"
    networks:
      tp5-bcc362:
        ipv4_address: 10.5.0.7
    depends_on:
     - api

networks:
  tp5-bcc362:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16

# Names our volume
volumes:
  my-db: